### ISSUE TITLE
Verifying packages is slow

### ISSUE THREAD

**Issue by stevenh** [awalsh128/cache-apt-pkgs-action#103]
We tried this action to improve our apt install performance in our workflows and once cached it was often actually slower than just performing the `apt-get install`.

I did a bit of digging and the main delay was "Verifying packages" process which is taking about 0.7s per package listed.

Testing locally `apt-cache show ${package}` is ~40ms where as on github is ~700ms.

Given this and the current flow we could be spending ~1.4s per package just calling `apt-cache show`.

**Comment by awalsh128** [comment]
Re-opening as the fix introduced a regression break (see https://github.com/awalsh128/cache-apt-pkgs-action/pull/104#issuecomment-1785930399)

**Comment by awalsh128** [comment]
I am in the process of moving the code to golang and started with this functionality.

https://github.com/awalsh128/cache-apt-pkgs-action/pull/117

I'll close this out once a release is ready.

**Comment by awalsh128** [comment]
https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.4.0 now has the Golang version of the querying component and the fix is incorporated.
