### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by HadrienG2** [awalsh128/cache-apt-pkgs-action#122]
I need it to cut the GitHub actions node20 warnings spam ;)

**Comment by awalsh128** [comment]
Just going to reissue this release tomorrow with the new version and force reload bump.

**Comment by awalsh128** [comment]
https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.4.1 now out. Please try again.

**Comment by samsonjs** [comment]
This still uses actions/upload-artifact@v3 which is on node16 too. There's a [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) to getting on v4.

**Comment by awalsh128** [comment]
Aw man. Okay I'll create a PR myself to make sure we don't do this again.

**Comment by samsonjs** [comment]
@awalsh128 Might be a false alarm and if so sorry for the goose chase! I just got a clean run with no warnings using 1.4.1

**Comment by HadrienG2** [comment]
1.4.1 runs fine and warnings-free here.

**Comment by awalsh128** [comment]
Okay cool. No worries about the false alarm. Glad it worked out. I'll update the tags and make it a release tomorrow.

**Comment by samsonjs** [comment]
Fantastic, thank you!
