### ISSUE TITLE
arm64 support.

### ISSUE THREAD

**Issue by awalsh128** [awalsh128/cache-apt-pkgs-action#128]
This came up as a result of https://github.com/awalsh128/cache-apt-pkgs-action/pull/127 involving @atilsensalduz and @koppor. The PR should fix the issue as a workaround. Issue originally came up because binaries were being used compiled for amd64 in the new `apt-query` command being used in the bash scripts.

Still need to add the regression to the CI. I authorized BuildJet as suggested in the PR thread but it looks like there is no free tier. On first look at the [pricing](https://buildjet.com/for-github-actions/docs/about/pricing) I shouldn't exceed $0.01 but still need to make sure to avoid a surprise bill.

I also saw this https://github.com/pguyot/arm-runner-action/blob/main/action.yml and am wondering if we could use this as an alternative (will need to reproduce).

**Comment by awalsh128** [comment]
Published https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.4.2 as a pre-prod release.

@koppor and/or @atilsensalduz can you confirm this works for you and I will mark it as prod ready?

**Comment by awalsh128** [comment]
Actually just run against `@master`. I was able to address another issue #98 and am going to include it in a repackaged release of v1.4.2 if it works.

**Comment by atilsensalduz** [comment]
Hey @awalsh128, I've tested 1.4.2 it worked on ARM instances in my environment

**Comment by koppor** [comment]
`@master` Works here, too.

**Comment by awalsh128** [comment]
Thanks for confirming. Going to reroll the release with that other fix and update this issue when ready.

**Comment by awalsh128** [comment]
https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.4.2 is now in prod.
