### ISSUE TITLE
Error about apt package list being not signed

### ISSUE THREAD

**Issue by Yelinz** [awalsh128/cache-apt-pkgs-action#131]
I assume this has nothing to do with this action but rather the microsoft apt repository. Close the issue if that is the case.

Pipeline failed on 24-Apr-2024 09:23
New file on the repository was created on: 24-Apr-2024 09:03 
Therefore I assume this is a microsoft problem

The relevant failed pipeline:
https://github.com/projectcaluma/alexandria/actions/runs/8813952473/job/24193633911
```
09:23:08.006 Updating APT package list...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

**Comment by thoraage** [comment]
Work around it by using `ubuntu-20.04` instead of `ubuntu-latest`
