### ISSUE TITLE
Migrate from apt to CLI safe alternatives

### ISSUE THREAD

**Issue by awalsh128** [awalsh128/cache-apt-pkgs-action#23]
The action will report CLI instability warning messages.

`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

This is because it isn't intended to be a non-interactive command. There are alternatives however as demonstrated in this [StackExchange post](https://askubuntu.com/questions/341178/how-do-i-get-details-about-a-package-which-isnt-installed). The scripts should get migrated eventually.

**Comment by pablgonz** [comment]
@awalsh128 `apt-fast` available by default :D

**Comment by pablgonz** [comment]
@awalsh128 The truth is that I am not an expert on this topic, I know it is stable and much faster when downloading and updating, it is constantly improving and no bugs are seen (not in the official repo at least).
