### ISSUE TITLE
Validating action arguments error

### ISSUE THREAD

**Issue by akaszynski** [awalsh128/cache-apt-pkgs-action#24]
I'm getting an error with just:

```
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libosmesa6-dev libgl1-mesa-dev python3-tk pandoc git-restore-mtime
          version: 1.0
```

Any idea what I'm doing wrong? Seems like it's correct. It fails with or without `refresh`.

Output from https://github.com/pyvista/pyvista/runs/7330225499?check_suite_focus=true:

```
...
2022-07-13T22:12:17.4876544Z ##[endgroup]
2022-07-13T22:12:17.6304815Z Validating action arguments (version='1', packages='libosmesa6-dev libgl1-mesa-dev python3-tk pandoc git-restore-mtime')...
2022-07-13T22:12:17.6331746Z ##[error]Process completed with exit code 1.
2022-07-13T22:12:17.6549645Z Post job cleanup.
...
```

**Comment by pablgonz** [comment]
@akaszynski  try with `uses: awalsh128/cache-apt-pkgs-action@v1.0.2`

**Comment by awalsh128** [comment]
What @pablgonz said. :) It has had some big patches since then.

**Comment by akaszynski** [comment]
Still seems like it's failing in https://github.com/pyvista/pyvista/pull/2985

**Comment by pablgonz** [comment]
@akaszynski Update versión number `version = 1.1`

**Comment by akaszynski** [comment]
```

Unable to resolve action `awalsh128/cache-apt-pkgs-action@v1.1`, unable to find version `v1.1`

```

**Comment by awalsh128** [comment]
Not sure if Pablo was referring to v1.0.2

**Comment by akaszynski** [comment]
`v1.0.2` fails for me as well. You can check out the failure on https://github.com/pyvista/pyvista/pull/2985 if you're interested.

**Comment by awalsh128** [comment]
Hey @akaszynski, please take a look at https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.0.3. It has the latest fixes for caching.

**Comment by akaszynski** [comment]
`v1.0.3` worked. Thanks!
