### ISSUE TITLE
Optimize initial APT install with `apt-fast`.

### ISSUE THREAD

**Issue by awalsh128** [awalsh128/cache-apt-pkgs-action#26]
[As mentioned in another issue](https://github.com/awalsh128/cache-apt-pkgs-action/issues/21#issuecomment-1182595956), installs can be drastically sped up using `apt-fast`. It would be nice to introduce some of these efficiencies into the action as well.

**Comment by awalsh128** [comment]
To install as documented from the GitHub site:

```sh
sudo add-apt-repository ppa:apt-fast/stable
sudo apt-get update
sudo apt-get -y install apt-fast
```

**Comment by pablgonz** [comment]
According to (https://github.com/actions/virtual-environments), `apt-fast` is available by default in all distributions. 

I believe that the speed, especially when using `cache` is considerably increased by using:

```
apt-fast -y install --no-install-recommends
```

By default `apt` installs the recommendations, but they are not necessary (in most cases) and if they are the user should make them explicit (in my humble opinion).

**Comment by awalsh128** [comment]
Perfect, thanks @pablgonz. I should be able to implement this by end of next week.

**Comment by pablgonz** [comment]
Jeje...Any reason not to upgrade to `actions/cache@v3`?

**Comment by awalsh128** [comment]
None at all. Updated in staging and master.

**Comment by awalsh128** [comment]
Feature now in master. Will put this into the v1.1.0 release.
