### ISSUE TITLE
cut binary path in ubuntu image is different from pre cache script

### ISSUE THREAD

**Issue by rlardy-ulule** [awalsh128/cache-apt-pkgs-action#28]
### Problem
Hi,
I tried to use this action to install packages but it throws me an error because the `cut` command declared [here](https://github.com/awalsh128/cache-apt-pkgs-action/blob/704b3e1a6451ca43cf8a6d38a302080d0c2a4fbd/pre_cache_action.sh#L62) is different from the one set up in the **ubuntu-18.04** image I use for my workflows.

When I run `command -v cut` inside my workflow it displays this : `/usr/bin/cut` instead of `/bin/cut`

### Solution

Add the `$(command -v cut)` in the [pre_cache_action.sh](https://github.com/awalsh128/cache-apt-pkgs-action/blob/704b3e1a6451ca43cf8a6d38a302080d0c2a4fbd/pre_cache_action.sh) instead of `/bin/cut` to ensure that the binary will always be called from the correct path no matter the distro.

**Comment by PeterBowman** [comment]
This was fixed in https://github.com/awalsh128/cache-apt-pkgs-action/pull/17 for v1.0.2, but it's still there at v1.0.3.

**Comment by awalsh128** [comment]
Apologies. This was a regression due to sync'ng branches. I fixed and rerolled this into a new v1.0.3

**Comment by rlardy-ulule** [comment]
It works now, thanks a lot !
