### ISSUE TITLE
Error when some of the dependencies are already installed

### ISSUE THREAD

**Issue by krupkat** [awalsh128/cache-apt-pkgs-action#36]
Hello, thanks for the super useful repo!

I have an issue when caching the libgtk-3-dev package on Ubuntu 22.04, excerpt from my workflow:

```
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@v1.1.0
      with:
          packages: libgtk-3-dev
```

Here is the error log:

```
...
09:49:08   * Caching libharfbuzz-gobject0 to /home/runner/cache-apt-pkgs/libharfbuzz-gobject0:2.7.4-1ubuntu3.1.tar.gz...
09:49:08     done (compressed size 28K).
09:49:08   * Caching libharfbuzz-icu0 to /home/runner/cache-apt-pkgs/libharfbuzz-icu0:2.7.4-1ubuntu3.1.tar.gz...
09:49:08     done (compressed size 8.0K).
E: Regex compilation error - Invalid range end
E: No packages found
09:49:08   * Caching libharfbuzz0b[2.7.4-1ubuntu3] to /home/runner/cache-apt-pkgs/libharfbuzz0b[2.7.4-1ubuntu3].tar.gz...
dpkg-query: error: --listfiles needs a valid package name but 'libharfbuzz0b[2.7.4-1ubuntu3]' is not: illegal package name in specifier 'libharfbuzz0b[2.7.4-1ubuntu3]': character '[' not allowed (only letters, digits and characters '-+._')
Use --help for help about querying packages.
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
Error: Process completed with exit code 123.
```

I believe the get_dep_packages function will have to be updated to better handle the output from `apt --dry-run`. Here is what I get when running `apt install --dry-run --yes libgtk-3-dev | grep "^Inst" | grep harfbuzz`:

```
Inst libharfbuzz0b [2.7.4-1ubuntu3] (2.7.4-1ubuntu3.1 Ubuntu:22.04/jammy-updates, Ubuntu:22.04/jammy-security [amd64])
Inst gir1.2-harfbuzz-0.0 (2.7.4-1ubuntu3.1 Ubuntu:22.04/jammy-updates, Ubuntu:22.04/jammy-security [amd64])
Inst libharfbuzz-icu0 (2.7.4-1ubuntu3.1 Ubuntu:22.04/jammy-updates, Ubuntu:22.04/jammy-security [amd64])
Inst libharfbuzz-gobject0 (2.7.4-1ubuntu3.1 Ubuntu:22.04/jammy-updates, Ubuntu:22.04/jammy-security [amd64])
Inst libharfbuzz-dev (2.7.4-1ubuntu3.1 Ubuntu:22.04/jammy-updates, Ubuntu:22.04/jammy-security [amd64])
```

See the extra version number in square brackets on line 1 which means that there is already a 2.7.4-1ubuntu3 version of the libharfbuzz0b package installed and it will be replaced by the 2.7.4-1ubuntu3.1 version. 

The other dependencies are fresh installs, so `awk '{print $2 $3}' ` works fine to extract the version number.

**Comment by awalsh128** [comment]
Started a possible fix. It is succeeding locally but still need to run against new regression test.

If you want, you can try it out yourself from `dev` branch.

**Comment by krupkat** [comment]
The fix from the `dev` branch worked, thanks a lot!

**Comment by awalsh128** [comment]
Great to hear. I'll update the issue once I have a release.

**Comment by awalsh128** [comment]
[v1.1.0 has been patched with fixes.](https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.1.0)

**Comment by krupkat** [comment]
Thank you! Working great now!
