### ISSUE TITLE
Improved package files compression with zstd.

### ISSUE THREAD

**Issue by awalsh128** [awalsh128/cache-apt-pkgs-action#46]
Mentioned in issue #45 by @tamascsaba
> Other improvement what I suggest is use zstd compression. It is much faster and supported in hosted runners.:
https://github.com/actions/virtual-environments/issues/89
You can use with: tar -caf package.tar.zst package-directory

Will perform some due diligence and update this when I get a chance.

**Comment by awalsh128** [comment]
Looks like the main citing of this performance is from FB engineering (who designed it) which looks impressive.
https://engineering.fb.com/2016/08/31/core-data/smaller-and-faster-data-compression-with-zstandard
The tested corpus matches our use case too (binaries < 51MB).

Just curious, have you observed this performance increase in the wild too @tamascsaba?

**Comment by tamascsaba** [comment]
Yes the decompress speed of zstd is amazing 👍 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/3479963/183356389-a61cf2e4-5953-456d-976d-b3b0092013b0.png">
I checked and you use `action/cache` and maybe it is worth it to compress with zstd or gzip or anything else, because `action/cache` compress with zstd by default and you will compress twice.

**Comment by awalsh128** [comment]
Ah good point. I think you mean to not compress?

**Comment by tamascsaba** [comment]
Taking a look at the performance differences is worth it in my opinion. For example try to install a bigger package and cache without compress or only use tar or compress with zstd or compress with gzip.

**Comment by awalsh128** [comment]
Was thinking this over and may omit compression entirely since the cache action already performs compression. This would reduce the cycles needed to backup the files too. May run a benchmark to test this hypothesis against a fairly large package.

**Comment by awalsh128** [comment]
Did some testing and concluded it would be faster to remove compression altogether, especially considering that the actions/cache already does this.
