### ISSUE TITLE
Permission denied error during caching installed packages.

### ISSUE THREAD

**Issue by dj12djdjs** [awalsh128/cache-apt-pkgs-action#47]
While attempting to cache `redis-server`

```
21:11:14   * Caching redis-server to /home/runner/cache-apt-pkgs/redis-server:5:5.0.7-2ubuntu0.1.tar.gz...
tar: etc/redis/redis.conf: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 123.
```
Full Log:
https://github.com/dj12djdjs/apt-cache-redis/runs/8101754369?check_suite_focus=true

Action:
https://github.com/dj12djdjs/apt-cache-redis/blob/main/.github/workflows/blank.yml

**Comment by awalsh128** [comment]
This may just be a simple of case of needing sudo. Point your action rev towards dev and try again. I'll set up a regression sometime tomorrow when I can along with a new release.

**Comment by dj12djdjs** [comment]
@awalsh128 That did the trick! Thanks for the patch!

https://github.com/dj12djdjs/apt-cache-redis/runs/8127482677?check_suite_focus=true

**Comment by awalsh128** [comment]
I release a patch as `[v1.1.1](https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.1.1)` and updated the `v1` tag to match so you can switch off of dev now.
