### ISSUE TITLE
Uses deprecated github `set-output` command

### ISSUE THREAD

**Issue by jrochkind** [awalsh128/cache-apt-pkgs-action#58]
Following shows up in output for step using this action. 

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

At first I suspected you were using an old version of `actions/cache`, which would trigger this warning.  But no, it looks like you are [using current actions/cache@v3](https://github.com/awalsh128/cache-apt-pkgs-action/blob/fc1d3efd6eb95068a842f61d365490601eb20fd2/action.yml#L48)

However, you are maybe actually directly calling set-output? 

https://github.com/awalsh128/cache-apt-pkgs-action/blob/fc1d3efd6eb95068a842f61d365490601eb20fd2/action.yml#L61-L62

It seems like you will have to change this implementation to avoid the deprecation warnings, and keep working once the `set-output` command is "disabled soon"? 

Looks like technically "soon" is actually about 6 months probably:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

— https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by awalsh128** [comment]
Thanks for bringing this up. I had been meaning to address this. 

Updated the code to reflect the update and it is released as a patch v1.1.2. I always update the latest and v1 tags as well when a new release happens FYI. Going to close this but feel free to re-open if you have anymore issues.

**Comment by jrochkind** [comment]
Thanks! Appears to work well for me!
