### ISSUE TITLE
skip installing apt-fast on cache hit

### ISSUE THREAD

**Issue by daaku** [awalsh128/cache-apt-pkgs-action#60]
Would it be possible to skip installing `apt-fast` if there is a cache hit? Maybe the installation can be moved to right before it's use in `install_and_cache_pkgs`?

**Comment by awalsh128** [comment]
Sure that should be easy to do. The download of the tool should be fast. Are you seeing a slowdown or just from looking at the code?

**Comment by daaku** [comment]
I only measured it locally and it seemed like an unnecessary slowdown for the cache hit case since it isn't used in that flow.

**Comment by awalsh128** [comment]
I agree, it can be moved. Out of curiosity, what kind of latency were you seeing?

**Comment by daaku** [comment]
I was seeing 1.2s locally from my laptop to curl the `apt-fetch` installer CLI.
