### ISSUE TITLE
Failed to cache package ca-certificates-java

### ISSUE THREAD

**Issue by SilverRainZ** [awalsh128/cache-apt-pkgs-action#63]
```
 11:16:56 Caching 157 installed packages...
11:16:56   * Caching fonts-droid-fallback to /home/runner/cache-apt-pkgs/fonts-droid-fallback:1:6.0.1r16-1.1.tar.gz...
11:16:57     done (compressed size 3.7M).
11:16:57   * Caching poppler-data to /home/runner/cache-apt-pkgs/poppler-data:0.4.9-2.tar.gz...
11:16:58     done (compressed size 4.0M).
11:16:58   * Caching libpcsclite1 to /home/runner/cache-apt-pkgs/libpcsclite1:1.8.26-3.tar.gz...
11:16:58     done (compressed size 24K).
11:16:58   * Caching openjdk-11-jre-headless to /home/runner/cache-apt-pkgs/openjdk-11-jre-headless:11.0.17+8-1ubuntu2~20.04.tar.gz...
11:17:06     done (compressed size 57M).
11:17:06   * Caching default-jre-headless to /home/runner/cache-apt-pkgs/default-jre-headless:2:1.11-72.tar.gz...
11:17:06     done (compressed size 4.0K).
11:17:06   * Caching ca-certificates-java to /home/runner/cache-apt-pkgs/ca-certificates-java:20190405ubuntu1.tar.gz...
tar: etc/default/cacerts: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 123.
```

See: https://github.com/SilverRainZ/bullet/actions/runs/3494642450/jobs/5854329890

**Comment by awalsh128** [comment]
I'll need more info about that file. Use the `@dev` version of the action and add the `debug: true` option to the it. Run again and then link to the run log for me.

**Comment by SilverRainZ** [comment]
Sigh, after using the dev version, the error disappears: https://github.com/SilverRainZ/bullet/actions/runs/3506432340/jobs/5873490522

**Comment by awalsh128** [comment]
That's okay, it's a good thing. :smile: There is a fix for permission denied errors forthcoming. Stay on this version for now. I have the `dev` changes soaking in `staging` and will do a release soon (maybe in the next 2 days). I'll update the ticket here and you can flip back to `v1` once it is released.

**Comment by awalsh128** [comment]
Published the latest version of the action which should fix your issue.

https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.2.0

Once you confirm the fix, you can close this out.

**Comment by SilverRainZ** [comment]
The v1.2.0 works well, thank you :D
