### ISSUE TITLE
validate_bool used before including the library

### ISSUE THREAD

**Issue by tueda** [awalsh128/cache-apt-pkgs-action#68]
Currently, the action leads to the following (harmless) error message:
```
/home/runner/work/_actions/awalsh128/cache-apt-pkgs-action/v1/pre_cache_action.sh: line 6: validate_bool: command not found
```

Perhaps, `validate_bool "${debug}" debug 1` in `pre_cache_action`:
https://github.com/awalsh128/cache-apt-pkgs-action/blob/982de21c87c4fde6433eb81e8d8485f122b68bb8/pre_cache_action.sh#L3-L11
can be delayed after `lib.sh` has been included.

**Comment by awalsh128** [comment]
Thank you for reporting this. I downgraded the `v1` and `latest` tags so this release doesn't affect your workflows. Taking a look at this issue and will reroll the most recent release today.

**Comment by awalsh128** [comment]
Hi @tueda, the strange thing is that my CI didn't catch this but I may have not tested this scenario correctly. Can you give me the args that you used?

**Comment by awalsh128** [comment]
After the rerelease, going to omit `set -e` and address the suppression at the affected lines so this gets caught in the future.

**Comment by awalsh128** [comment]
Turned on `set -e` and am now able to replicate the behavior.
https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/3542415556

Verified fix is now working.
https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/3542442682

Will rereoll shortly.

**Comment by awalsh128** [comment]
Okay, rerolled `v1.2.0` under the latest commit with fix https://github.com/awalsh128/cache-apt-pkgs-action/commit/9bc3e210f3df554738deb576965ea96f57c5f501. 

@tueda @tkoyama010, delete the latest dependency and retrieve latest under this tag.
