### ISSUE TITLE
Issue upgrading to 1.2.2

### ISSUE THREAD

**Issue by akaszynski** [awalsh128/cache-apt-pkgs-action#83]
We're seeing failures when upgrading to 1.2.2 in https://github.com/pyvista/pyvista/pull/3773

If this is related to caching, is there a way you could reset the cache for new versions? That way dependabot PRs don't instantly fail.

Workflow traceback:

```
09:10:18 Reading from main requested packages manifest...
09:10:18 - git-restore-mtime 2019.11-1
09:10:18 - libgl1-mesa-dev 21.2.6-0ubuntu0.1~20.04.2
09:10:18 - libosmesa6-dev 21.2.6-0ubuntu0.1~20.04.2
09:10:18 - pandoc 2.5-3build2
09:10:18 - python3-tk 3.8.10-0ubuntu1~20.04
09:10:18 done

ls: cannot access '/home/runner/cache-apt-pkgs/*.tar': No such file or directory
```

**Comment by awalsh128** [comment]
I set the latest release back to 1.2.1 so dependabot sees this instead. Will take a look at the failure. Please try again.

**Comment by awalsh128** [comment]
FYI, I need to revert the `latest` and `v1` tag while I look into this.

**Comment by awalsh128** [comment]
@akaszynski could you share your action invocation with me? Also, did this still happen after changing the input version?

**Comment by awalsh128** [comment]
Okay, that issue has now been fixed. Latest release addresses this #82
